# Generated by Django 3.0.5 on 2020-04-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=34, verbose_name='Название ивента')),
                ('event_text', models.TextField(verbose_name='Описание ивента')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('event_status', models.CharField(default='Еще не начался', max_length=20, verbose_name='Текущее состояние ивента')),
                ('event_photo', models.FileField(blank=True, null=True, upload_to='event_media', verbose_name='Изображение для ивента')),
                ('competitors_id_list', models.TextField(blank=True, default='', verbose_name='Список участников')),
            ],
        ),
    ]
