# Generated by Django 3.0.5 on 2020-04-24 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(default=datetime.datetime(2020, 4, 24, 11, 21, 47, 414323, tzinfo=utc), max_length=50, verbose_name='Текущее состояние ивента'),
            preserve_default=False,
        ),
    ]
