# Generated by Django 3.0.5 on 2020-04-25 23:28

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publish_date',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
