# Generated by Django 3.0.5 on 2020-04-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200425_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Время начала ивента'),
        ),
    ]
