# Generated by Django 3.0.5 on 2020-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200424_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение для ивента'),
        ),
    ]
