# Generated by Django 3.0.5 on 2020-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='CodeBattle/media/images/', verbose_name='Изображение для ивента'),
        ),
    ]
