# Generated by Django 3.0.5 on 2020-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200424_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение для ивента'),
        ),
    ]
