# Generated by Django 3.0.5 on 2020-04-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200424_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competitors_id_list',
            field=models.TextField(default=None, verbose_name='Список участников'),
            preserve_default=False,
        ),
    ]
