# Generated by Django 3.0.5 on 2020-04-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_competitors_id_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='competitors_id_list',
        ),
    ]
