# Generated by Django 3.0.5 on 2020-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_competitors_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competitors_id_list',
            field=models.TextField(default='', verbose_name='Список участников'),
            preserve_default=False,
        ),
    ]
