# Generated by Django 3.0.5 on 2020-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_competitors_id_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='competitors_id_list',
            field=models.TextField(blank=True, verbose_name='Список участников'),
        ),
    ]
