# Generated by Django 3.0.5 on 2020-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200424_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_text',
            field=models.TextField(max_length=300, verbose_name='Описание ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=34, verbose_name='Название ивента'),
        ),
    ]
