# Generated by Django 3.0.5 on 2020-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200425_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='competitors_id_list',
            field=models.TextField(blank=True, null=True, verbose_name='Список участников'),
        ),
    ]
