# Generated by Django 3.0.5 on 2020-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200425_1405'),
        ('events', '0014_auto_20200425_1836'),
    ]

    operations = [
    ]
