# Generated by Django 3.0.5 on 2020-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='Empty', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='sirname',
            field=models.CharField(blank=True, default='Empty', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Empty', max_length=254),
        ),
    ]
