# Generated by Django 3.0.5 on 2020-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200424_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_list',
            field=models.TextField(null=True, verbose_name='Список ID битв'),
        ),
    ]
