# Generated by Django 3.0.5 on 2020-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_event_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event_list',
            field=models.TextField(default='', verbose_name='Список ID битв'),
        ),
    ]
