# Generated by Django 3.0.5 on 2020-04-26 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_auto_20200426_0051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeEnd', models.DateTimeField(verbose_name='Время завершения битвы')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во вопросов за 1 раунд')),
                ('task_time', models.IntegerField(default=30, verbose_name='Время на один вопрос')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Событие')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(default=1, verbose_name='ID_IN_BATTLE')),
                ('av_count', models.IntegerField(default=0, verbose_name='ANSWER_VARIANTS_COUNT')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('image_url', models.FileField(blank=True, null=True, upload_to=None, verbose_name='Изображение (Если нужно)')),
                ('Battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Battles.Battle')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_task', models.IntegerField(blank=True, null=True, verbose_name='Текущий вопрос')),
                ('Battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Battles.Battle')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='Первый участник')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Второй участник')),
            ],
        ),
        migrations.CreateModel(
            name='Participent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isReady', models.BooleanField(verbose_name='Готовность')),
                ('Battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Battles.Battle')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(default=1, verbose_name='ID_IN_QUESTION')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('correctly', models.BooleanField(verbose_name='Верный ли вариант')),
                ('Task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Battles.Task')),
            ],
        ),
    ]
