# Generated by Django 3.0.5 on 2020-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во вопросов за 1 раунд'),
        ),
        migrations.AddField(
            model_name='battle',
            name='time',
            field=models.IntegerField(default=30, verbose_name='Время на один вопрос'),
        ),
        migrations.AddField(
            model_name='round',
            name='current_task',
            field=models.IntegerField(blank=True, null=True, verbose_name='Текущий вопрос'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Изображение (Если нужно)'),
        ),
    ]
