# Generated by Django 3.0.5 on 2020-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battles', '0002_auto_20200426_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='t_id',
            field=models.IntegerField(default=1, verbose_name='ID_IN_BATTLE'),
        ),
    ]
