# Generated by Django 3.0.5 on 2020-04-25 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Battles', '0003_contact_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
