# Generated by Django 3.0.5 on 2020-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Battles', '0002_auto_20200425_1836'),
        ('Battles', '0004_battle_timestamp'),
    ]

    operations = [
    ]
