# Generated by Django 3.0.5 on 2020-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battles', '0005_merge_20200425_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_contact_friends_+', to='Battles.Contact'),
        ),
    ]
