# Generated by Django 3.0.5 on 2020-04-25 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Battles', '0006_contact_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isReady', models.BooleanField(verbose_name='Готовность')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pair',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='currentPair',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='battle',
            name='TimeEnd',
            field=models.DateTimeField(verbose_name='Время завершения битвы'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='TimeStart',
            field=models.DateTimeField(verbose_name='Время начала битвы'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
        migrations.AddField(
            model_name='round',
            name='Battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Battles.Battle'),
        ),
        migrations.AddField(
            model_name='round',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='Первый участник'),
        ),
        migrations.AddField(
            model_name='round',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Второй участник'),
        ),
        migrations.AddField(
            model_name='participent',
            name='Battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Battles.Battle'),
        ),
        migrations.AddField(
            model_name='participent',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
