# Generated by Django 3.0.5 on 2020-04-25 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Battles', '0007_auto_20200425_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='Первый участник'),
        ),
    ]
