# Generated by Django 3.0.5 on 2020-04-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Battles', '0008_auto_20200425_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='TimeStart',
        ),
    ]
